blank_issues_enabled: false
contact_links:
  - name: "Buy POST VOID on Steam"
    url: "https://store.steampowered.com/app/1285670/Post_Void/"
    about: "Support the original developers at YCJY Games by purchasing the PC game!"
